// 根据官方公开地区列表整理，复核日期 2026-09-14；与 GitHub 检测项目无运行依赖。
// 来源 URL 和适用入口见 ai-regions.ts。代码只表达地区范围，账号与子地区条件另行保留。
export const OPENAI_REGIONS = `
AD AE AF AG AL AM AO AR AT AU AW AX AZ BA BB BD BE BG BH BI BL BM BN BO BR BS
BT BW BZ CA CD CF CG CH CI CL CM CO CR CV CY CZ DE DJ DK DM DO DY DZ EC EE EG
ER ES ET FI FJ FM FO FX GA GD GE GF GH GL GM GN GP GQ GR GT GW GY HN HR HT HU
HV ID IE IL IN IQ IS IT JM JO JP KE KG KH KI KM KN KR KW KY KZ LA LB LC LI LK
LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MQ MR MT MU MV MW MX MY MZ
NA NC NE NG NI NL NO NP NR NZ OM PA PE PF PG PH PK PL PM PS PT PW PY QA RE RO
RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SZ TD TF TG TH TJ TL
TM TN TO TR TT TV TW TZ UA UG UK US UY UZ VA VC VN VU WF WS YE YT YU ZA ZM ZW
`
  .trim()
  .split(/\s+/)

export const CLAUDE_REGIONS = `
AD AE AG AL AM AO AR AT AU AZ BA BB BD BE BG BH BI BN BO BR BS BT BW BZ CA CF
CG CH CI CL CM CO CR CV CY CZ DE DJ DK DM DO DY DZ EC EE EG ER ES ET FI FJ FM
FX GA GD GE GH GM GN GQ GR GT GW GY HN HR HT HU HV ID IE IL IN IQ IS IT JM JO
JP KE KG KH KI KM KN KR KW KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG
MH MK ML MN MR MT MU MV MW MX MY MZ NA NE NG NI NL NO NP NR NZ OM PA PE PG PH
PK PL PS PT PW PY QA RO RW SA SB SC SD SE SG SI SK SL SM SN SO SR SS ST SV SZ
TD TG TH TJ TM TN TO TP TR TT TV TW TZ UA UG UK US UY UZ VA VC VN VU WS YU ZA
ZM ZW
`
  .trim()
  .split(/\s+/)

export const GEMINI_WEB_REGIONS = `
AD AE AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BG BH BI BL BM BN BO
BQ BR BS BT BW BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CV CW CX CY CZ DE DJ
DK DM DO DY DZ EC EE EG EH ER ES ET FI FJ FK FM FO FX GA GD GE GF GG GH GI GL
GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU HV ID IE IL IM IN IO IQ IS IT
JE JM JO JP KE KG KH KI KM KN KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA
MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF
NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO
RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SZ TC TD TF TG TH
TJ TK TM TN TO TP TR TT TV TW TZ UA UG UK UM US UY UZ VA VC VE VG VI VN VU WF
WS XK YE YT YU ZA ZM ZW
`
  .trim()
  .split(/\s+/)

export const GEMINI_API_REGIONS = `
AD AE AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BG BH BI BL BM BN BO
BQ BR BS BT BW BZ CA CC CD CF CG CH CI CK CL CM CO CR CV CW CX CY CZ DE DJ DK
DM DO DY DZ EC EE EG EH ER ES ET FI FJ FK FM FO FX GA GD GE GF GG GH GI GL GM
GN GQ GR GS GT GU GW GY HM HN HR HT HU HV ID IE IL IM IN IO IQ IS IT JE JM JO
JP KE KG KH KI KM KN KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME
MG MH MK ML MN MP MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU
NZ OM PA PE PG PH PK PL PM PN PR PS PT PW PY QA RE RO RW SA SB SC SD SE SG SH
SI SK SL SM SN SO SR SS ST SV SZ TC TD TG TH TJ TK TM TN TO TP TR TT TV TW TZ
UA UG UK UM US UY UZ VA VC VE VG VI VN VU WF WS XK YE YU ZA ZM ZW
`
  .trim()
  .split(/\s+/)

// ISO 3166 映射：UN M49 公开表 https://unstats.un.org/unsd/methodology/m49/overview
// TWN/TW 为 ISO 台湾地区码，作为 Gemini 页面响应的兼容项单独补充。
export const REGION_ALPHA3 = new Map(
  `
ABW:AW AFG:AF AGO:AO AIA:AI ALA:AX ALB:AL AND:AD ARE:AE ARG:AR ARM:AM
ASM:AS ATA:AQ ATF:TF ATG:AG AUS:AU AUT:AT AZE:AZ BDI:BI BEL:BE BEN:BJ
BES:BQ BFA:BF BGD:BD BGR:BG BHR:BH BHS:BS BIH:BA BLM:BL BLR:BY BLZ:BZ
BMU:BM BOL:BO BRA:BR BRB:BB BRN:BN BTN:BT BVT:BV BWA:BW CAF:CF CAN:CA
CCK:CC CHE:CH CHL:CL CHN:CN CIV:CI CMR:CM COD:CD COG:CG COK:CK COL:CO
COM:KM CPV:CV CRI:CR CUB:CU CUW:CW CXR:CX CYM:KY CYP:CY CZE:CZ DEU:DE
DJI:DJ DMA:DM DNK:DK DOM:DO DZA:DZ ECU:EC EGY:EG ERI:ER ESH:EH ESP:ES
EST:EE ETH:ET FIN:FI FJI:FJ FLK:FK FRA:FR FRO:FO FSM:FM GAB:GA GBR:GB
GEO:GE GGY:GG GHA:GH GIB:GI GIN:GN GLP:GP GMB:GM GNB:GW GNQ:GQ GRC:GR
GRD:GD GRL:GL GTM:GT GUF:GF GUM:GU GUY:GY HKG:HK HMD:HM HND:HN HRV:HR
HTI:HT HUN:HU IDN:ID IMN:IM IND:IN IOT:IO IRL:IE IRN:IR IRQ:IQ ISL:IS
ISR:IL ITA:IT JAM:JM JEY:JE JOR:JO JPN:JP KAZ:KZ KEN:KE KGZ:KG KHM:KH
KIR:KI KNA:KN KOR:KR KWT:KW LAO:LA LBN:LB LBR:LR LBY:LY LCA:LC LIE:LI
LKA:LK LSO:LS LTU:LT LUX:LU LVA:LV MAC:MO MAF:MF MAR:MA MCO:MC MDA:MD
MDG:MG MDV:MV MEX:MX MHL:MH MKD:MK MLI:ML MLT:MT MMR:MM MNE:ME MNG:MN
MNP:MP MOZ:MZ MRT:MR MSR:MS MTQ:MQ MUS:MU MWI:MW MYS:MY MYT:YT NAM:NA
NCL:NC NER:NE NFK:NF NGA:NG NIC:NI NIU:NU NLD:NL NOR:NO NPL:NP NRU:NR
NZL:NZ OMN:OM PAK:PK PAN:PA PCN:PN PER:PE PHL:PH PLW:PW PNG:PG POL:PL
PRI:PR PRK:KP PRT:PT PRY:PY PSE:PS PYF:PF QAT:QA REU:RE ROU:RO RUS:RU
RWA:RW SAU:SA SDN:SD SEN:SN SGP:SG SGS:GS SHN:SH SJM:SJ SLB:SB SLE:SL
SLV:SV SMR:SM SOM:SO SPM:PM SRB:RS SSD:SS STP:ST SUR:SR SVK:SK SVN:SI
SWE:SE SWZ:SZ SXM:SX SYC:SC SYR:SY TCA:TC TCD:TD TGO:TG THA:TH TJK:TJ
TKL:TK TKM:TM TLS:TL TON:TO TTO:TT TUN:TN TUR:TR TUV:TV TWN:TW TZA:TZ
UGA:UG UKR:UA UMI:UM URY:UY USA:US UZB:UZ VAT:VA VCT:VC VEN:VE VGB:VG
VIR:VI VNM:VN VUT:VU WLF:WF WSM:WS YEM:YE ZAF:ZA ZMB:ZM ZWE:ZW
  `
    .trim()
    .split(/\s+/)
    .map((pair): [string, string] => {
      const [alpha3, alpha2] = pair.split(':')
      return [alpha3, alpha2]
    }),
)
