/** Approved appearance system, Figma cneSvAGuLF6o64h19Lc8Vg / 29:2 (2026-09-21).
 * Shared by the renderer and native window tint; each theme has the same color roles.
 */
export type Appearance = 'light' | 'dark'

export const appearancePalettes = {
  classic: {
    light: {
      shell: '#F5F7FB',
      sidebar: '#FAFBFE',
      canvas: '#F5F7FB',
      surface: '#FFFFFF',
      'surface-alt': '#FAFBFE',
      border: '#E6EAF2',
      text: '#151F32',
      muted: '#4C5C76',
      primary: '#6857D8',
      'primary-hover': '#5846C3',
      'on-primary': '#FFFFFF',
      soft: '#F1EEFF',
      'soft-text': '#6857D8',
      'nav-selected': '#F1EEFF',
      'nav-text': '#4C5C76',
      'nav-muted': '#5F6E85',
      'nav-active-text': '#6857D8',
      'chart-2': '#8593AA',
      'chart-3': '#A8B4C8',
      track: '#E6EAF2',
      disabled: '#E6EAF2',
      'disabled-text': '#8593AA',
      success: '#0B785B',
      warning: '#A2650D',
      danger: '#BE4656',
      'success-soft': '#E7F5EF',
      'warning-soft': '#FFF1D8',
      'danger-soft': '#FBE7EE',
      focus: '#6857D8',
    },
    dark: {
      shell: '#252D3B',
      sidebar: '#252D3B',
      canvas: '#202733',
      surface: '#293241',
      'surface-alt': '#2D3747',
      border: '#414D60',
      text: '#EDF1F7',
      muted: '#ADB9CC',
      primary: '#B8ACF3',
      'primary-hover': '#CEC4FF',
      'on-primary': '#29223F',
      soft: '#3D3759',
      'soft-text': '#D3C9FF',
      'nav-selected': '#3E385D',
      'nav-text': '#D7DEEB',
      'nav-muted': '#ADB9CC',
      'nav-active-text': '#D3C9FF',
      'chart-2': '#95A5BC',
      'chart-3': '#73849E',
      track: '#3C485B',
      disabled: '#374253',
      'disabled-text': '#97A5BA',
      success: '#8ADEBF',
      warning: '#FFD086',
      danger: '#FFABBD',
      'success-soft': '#204D41',
      'warning-soft': '#594224',
      'danger-soft': '#5B2A41',
      focus: '#CEC4FF',
    },
  },
  iris: {
    light: {
      shell: '#F0E9FB',
      sidebar: '#E5D9F8',
      canvas: '#F8F5FC',
      surface: '#FFFDFE',
      'surface-alt': '#F2ECFA',
      border: '#D9CBEA',
      text: '#322343',
      muted: '#736183',
      primary: '#7446C8',
      'primary-hover': '#6035AD',
      'on-primary': '#FFFFFF',
      soft: '#EBDEFA',
      'soft-text': '#6034A8',
      'nav-selected': '#7446C8',
      'nav-text': '#463157',
      'nav-muted': '#6E5685',
      'nav-active-text': '#FFFFFF',
      'chart-2': '#A687D6',
      'chart-3': '#C2AEDF',
      track: '#E9DFF3',
      disabled: '#E9E1EF',
      'disabled-text': '#82708F',
      success: '#187157',
      warning: '#946013',
      danger: '#B82E4E',
      'success-soft': '#E7F5EF',
      'warning-soft': '#FFF1D8',
      'danger-soft': '#FBE7EE',
      focus: '#7446C8',
    },
    dark: {
      shell: '#30203F',
      sidebar: '#42295F',
      canvas: '#281B36',
      surface: '#352346',
      'surface-alt': '#3E2B51',
      border: '#5B4270',
      text: '#F7ECFF',
      muted: '#C1A7D3',
      primary: '#C6A0FF',
      'primary-hover': '#D4B8FF',
      'on-primary': '#35204D',
      soft: '#4B2E6D',
      'soft-text': '#DDC5FF',
      'nav-selected': '#C6A0FF',
      'nav-text': '#F3E3FF',
      'nav-muted': '#C7AEDC',
      'nav-active-text': '#35204D',
      'chart-2': '#9F7BCE',
      'chart-3': '#7D5DA7',
      track: '#53376B',
      disabled: '#49345A',
      'disabled-text': '#B79BCB',
      success: '#8ADEBF',
      warning: '#FFD086',
      danger: '#FFABBD',
      'success-soft': '#204D41',
      'warning-soft': '#594224',
      'danger-soft': '#5B2A41',
      focus: '#D8B8FF',
    },
  },
  cobalt: {
    light: {
      shell: '#E8EFFB',
      sidebar: '#CEDFF8',
      canvas: '#F2F7FE',
      surface: '#FBFDFF',
      'surface-alt': '#E9F0FC',
      border: '#C5D7F0',
      text: '#203B60',
      muted: '#5A759A',
      primary: '#2A62C4',
      'primary-hover': '#204E9E',
      'on-primary': '#FFFFFF',
      soft: '#DDE9FD',
      'soft-text': '#2055AB',
      'nav-selected': '#2A62C4',
      'nav-text': '#2B4F7F',
      'nav-muted': '#446085',
      'nav-active-text': '#FFFFFF',
      'chart-2': '#76A2E0',
      'chart-3': '#ABC9EE',
      track: '#DCE7F7',
      disabled: '#E0E9F5',
      'disabled-text': '#6F87A7',
      success: '#187157',
      warning: '#946013',
      danger: '#B82E4E',
      'success-soft': '#E7F5EF',
      'warning-soft': '#FFF1D8',
      'danger-soft': '#FBE7EE',
      focus: '#2A62C4',
    },
    dark: {
      shell: '#203552',
      sidebar: '#2B4A70',
      canvas: '#192D46',
      surface: '#223B59',
      'surface-alt': '#2A4567',
      border: '#3D6088',
      text: '#EBF4FF',
      muted: '#A4C0DF',
      primary: '#96BEFF',
      'primary-hover': '#BDD8FF',
      'on-primary': '#183D69',
      soft: '#304F78',
      'soft-text': '#C6DFFF',
      'nav-selected': '#96BEFF',
      'nav-text': '#E7F2FF',
      'nav-muted': '#B0CCEA',
      'nav-active-text': '#183D69',
      'chart-2': '#6896D2',
      'chart-3': '#4872A8',
      track: '#34577F',
      disabled: '#304C6C',
      'disabled-text': '#9FB9D7',
      success: '#8ADEBF',
      warning: '#FFD086',
      danger: '#FFABBD',
      'success-soft': '#204D41',
      'warning-soft': '#594224',
      'danger-soft': '#5B2A41',
      focus: '#C0DCFF',
    },
  },
  copper: {
    light: {
      shell: '#F4E8DF',
      sidebar: '#F0DDD0',
      canvas: '#FFF7EE',
      surface: '#FFFCF8',
      'surface-alt': '#FBF4ED',
      border: '#E7D8CC',
      text: '#3F2E25',
      muted: '#795D4F',
      primary: '#995D46',
      'primary-hover': '#824B37',
      'on-primary': '#FFF7EE',
      soft: '#F2E1D5',
      'soft-text': '#864E37',
      'nav-selected': '#995D46',
      'nav-text': '#654536',
      'nav-muted': '#795747',
      'nav-active-text': '#FFF7EE',
      'chart-2': '#B5846B',
      'chart-3': '#CEB39E',
      track: '#EDDED1',
      disabled: '#EBDDD2',
      'disabled-text': '#9A8272',
      success: '#187157',
      warning: '#946013',
      danger: '#B82E4E',
      'success-soft': '#E7F5EF',
      'warning-soft': '#FFF1D8',
      'danger-soft': '#FBE7EE',
      focus: '#995D46',
    },
    dark: {
      shell: '#382E29',
      sidebar: '#4B372E',
      canvas: '#302825',
      surface: '#3B302A',
      'surface-alt': '#42362F',
      border: '#615047',
      text: '#F8EEE7',
      muted: '#CFB9AA',
      primary: '#DFA586',
      'primary-hover': '#EEBA9B',
      'on-primary': '#3C251B',
      soft: '#594034',
      'soft-text': '#F0C0A4',
      'nav-selected': '#DFA586',
      'nav-text': '#F5E6D9',
      'nav-muted': '#D0B7A5',
      'nav-active-text': '#3C251B',
      'chart-2': '#C28A6B',
      'chart-3': '#9D7560',
      track: '#634C3F',
      disabled: '#534338',
      'disabled-text': '#B79A87',
      success: '#8ADEBF',
      warning: '#FFD086',
      danger: '#FFABBD',
      'success-soft': '#204D41',
      'warning-soft': '#594224',
      'danger-soft': '#5B2A41',
      focus: '#EEBA9B',
    },
  },
} as const

export type AppearancePaletteId = keyof typeof appearancePalettes
export type PaletteRole = keyof typeof appearancePalettes.classic.light
export type PaletteColors = Readonly<Record<PaletteRole, string>>
export const DEFAULT_PALETTE: AppearancePaletteId = 'classic'
export const DEFAULT_APPEARANCE: Appearance = 'light'
export const APPEARANCE_VERSION = '2'

export function isAppearancePalette(value: unknown): value is AppearancePaletteId {
  return typeof value === 'string' && Object.hasOwn(appearancePalettes, value)
}

/** v1 Iris used the neutral palette now named Classic. Run once for saved preferences. */
export function migrateAppearancePalette(value: unknown, version: unknown): AppearancePaletteId {
  if (version !== APPEARANCE_VERSION && value === 'iris') return 'classic'
  if (isAppearancePalette(value)) return value
  if (value === 'ember' || value === 'amber' || value === 'ruby') return 'copper'
  return DEFAULT_PALETTE
}
